version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - curl -L -o ./hoge.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.89.4/hugo_extended_0.89.4_Linux-64bit.tar.gz
      - mkdir -p ./bin && tar -xvf hoge.tar.gz -C ./bin
  pre_build:
    commands:
      - echo In pre_build phase..
      - echo Current directory is $CODEBUILD_SRC_DIR
      - ls -la
  build:
    commands:
      - ./bin/hugo -v
artifacts:
  files: "**/*"
  base-directory: public
