baseURL = 'http://example.org/' # TODO: そのうち決める必要がある
languageCode = 'ja-jp'
title = "Memo.Namo"
hasCJKLanguage = true
theme = "ananke"

[permalinks]
knowledge = "/:section/:filename/"

[markup]
  [markup.highlight]
    guessSyntax=true
    noClasses=false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 2

[[menu.main]]
name = "About"
url = "/about/"

[[menu.main]]
name = "Knowledge"
url = "/knowledge/"