baseURL = "/"
title = "Namoshika's memo"
theme = "docdock"
languageCode = "ja-jp"
hasCJKLanguage = true
uglyurls = true

[params]
themeStyle = "flex"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
identifier = "tw"
name = "<i class='fa fa-twitter'></i>"
url = "https://twitter.com/namoshika"
weight = 1

[[menu.shortcuts]]
identifier = "gh"
name = "<i class='fa fa-github'></i>"
url = "https://github.com/namoshika"
weight = 2